### ISSUE TITLE
Modules signing

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/driverkit#1]
**Motivation**
We want to help our users to make sure they run code coming from the Falcosecurity project by enabling

**Feature**

Make so that the builder uses the kernel module signing facility: https://www.kernel.org/doc/html/v4.10/admin-guide/module-signing.html

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
+1
L.

**Comment by kris-nova** [comment]
Strong +1 - Go! Let's make it happen.

**Comment by leogr** [comment]
+1
