### ISSUE TITLE
Absorb features from thought-machine/falco-probes

### ISSUE THREAD

**Issue by VJftw** [falcosecurity/driverkit#103]
👋 , I posted on the Kubernetes #falco Slack channel about our [thought-machine/falco-probes](https://github.com/thought-machine/falco-probes) project which automates the building and mirroring of eBPF kernel probes for Falco. We'd love to share and contribute some of our solutions to `driverkit` which help anyone else that has similar needs to us :smile:.

**Motivation**

We desire to deploy Falco without compiling kernel eBPF probes at runtime as we have a great interest in running Falco with the least amount of privileges possible and in a more immutable fashion. 

For us to do this, we download probes that our Kubernetes clusters might need at build-time and copy them into a `docker.io/falcosecurity/falco:0.29.1` based image. 

During our attempt to build this image, we came across the following hurdles:

1. eBPF probes for `amazonlinux2` and `cos` were missing from [download.falco.org/driver](https://download.falco.org/driver).
2. Falco drivers are re-uploaded every build (see https://prow.falco.org/view/s3/falco-prow-logs/logs/build-drivers-amazonlinux2-periodic/1430002167883763712) which risks file hash changes. This meant that we couldn't rely on the [download.falco.org/driver](https://download.falco.org/driver) repository as a driver source because we perform hash verification on all external files.
3. New kernels for an operating system are supported via a [PR process](https://github.com/falcosecurity/test-infra/pull/494) which adds a maintenance burden and human dependency.

It was clear that we needed to compile eBPF probes ourselves, where we encountered the following extra hurdle with `driverkit`:

4. `cos` is not supported and doesn't appear trivial to support for the accepted `kernelrelease + kernelversion` inputs as [Kernel headers are provided per `cos` Build ID](https://github.com/falcosecurity/falco/blob/0.29.1/scripts/falco-driver-loader#L329), i.e. Translating a `kernelrelease + kernelversion` to a Build ID programmatically isn't possible as no mapping appears to exist.

**Feature**

[thought-machine/falco-probes](https://github.com/thought-machine/falco-probes) is our solution to those 4 hurdles. I've summarised them below:

1. eBPF probes are built and mirrored.
2. Only mirror probes that aren't already mirrored.
3. To solve this, we endeavoured to dynamically build eBPF probes for all possible kernels associated with an operating system. This is possible if we can enumerate them, e.g.
	* `amazonlinux2`: Run `docker run --rm amazonlinux:2 yum --showduplicates list kernel-devel`. This is similar for all operating systems which include a package manager for distributing kernel updates.
	* `cos`: Is a bit trickier as there is no package manager. However, we can run `gsutil ls -r gs://cos-tools/ | grep "kernel-headers.tgz$" | cut -f4 -d/` to list all of the Build IDs of `cos`. This isn't specifically a list of kernels but is an enumerable list that we can trust to build kernel probes from. There will be duplicated probes as different BUILD IDs will likely share kernels.
4. With our solution to 3 in mind, we decided to use the items from the lists as inputs to building a probe. e.g. `amazonlinux2 + 4.14.77-86.82.amzn2` or `cos + 16108.470.11`. We refer to these items as *Kernel Package Name*s.

Detailed discovery and implementation of these solutions are documented in [thought-machine/falco-probes/docs/](https://github.com/thought-machine/falco-probes/blob/master/docs/).

In terms of supporting these features within `driverkit` and `test-infra`, I think:

1. Is trivial to do: Add `output.probe` field to each of the `**/*.yaml` files in https://github.com/falcosecurity/test-infra/tree/master/driverkit/config.
2. Is trivial to do: Check in the S3 bucket which probes already exist and only build + upload the missing ones.
3. and 4. Are not trivial to do: Our solution uses a different set of inputs to the build process than driverkit currently does (`kernelrelease + kernelversion` vs. `kernel package name`). Maybe we could support the `kernel package name` as a different input that obtains kernel sources + headers the same way that thought-machine/falco-probes does? If so, we could easily generate the driverkit YAML input files too with the `kernel package name` set. 

Any other ideas on this? How does this sound to you? :smile:

**Alternatives**

Described in *Motivation* 🤞. For solution 3). we could solve this for operating systems with package managers in `driverkit` by having a tool that generates the `kernelrelease + kernelversion` inputs by enumerating the available kernel packages. 

**Additional context**

Hopefully, we've covered the context in the _Motiviation_, but please ask us for more if you're missing any 😄.

**Comment by Issif** [comment]
Hello @VJftw,

Thank you for this really valuable issue. We love to discuss about in a Community Call:

```
Falco Weekly Community call every Wednesday (4:00pm to 5:00pm (UTC) (Zoom Details: 
https://zoom.us/my/cncffalcoproject )
```

or in our Slack Channel https://kubernetes.slack.com #falco

Driverkit and all ways to improve the UX with modules/probes are part of our current topics.

**Comment by leogr** [comment]
cc @FedeDP @dwindsor wdyt?

**Comment by dwindsor** [comment]
> cc @FedeDP @dwindsor wdyt?

I feel like we can close this. kernel-crawler integration solves a lot of the issues mentioned here.
