### ISSUE TITLE
driverkit doesn't build latest AmazonLinux2 configs 

### ISSUE THREAD

**Issue by dwindsor** [falcosecurity/driverkit#137]
The AmazonLinux2 builder fails to builder newer configs because it's unable to find `5.10.x` kernel releases.

**How to reproduce it**

Try to build a recent AmazonLinux2 kernel from the 5.10 series:

```shell
user@driverkit-vm:~/src/driverkit$ sudo ./_output/bin/driverkit docker --output-module /tmp/falco.ko --kernelversion=1 --kernelrelease=5.10.35-31.135.amzn2.x86_64 --driverversion=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4 --target=amazonlinux2
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="target amazonlinux2 needs to find both kernel and kernel-devel packages"
```

The AmazonLinux2 builder needs to be updated so it can find the latest `kernel` and `kernel-devel` packages.

**Screenshot**

Expected results:

![Screen Shot 2022-04-20 at 11 48 08 AM](https://user-images.githubusercontent.com/934449/164271216-f57eea00-43cf-4b20-b35d-326ef58ccd6b.png)

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel:
`Linux driverkit-vm 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

- Installation method:
from source

**Additional context**

**Comment by abroglesc** [comment]
Created #139 to address ebpf probe version not just kmod
