### ISSUE TITLE
[RFE] Add support for CentOS9 stream

### ISSUE THREAD

**Issue by e-minguez** [falcosecurity/driverkit#152]
**Motivation**

Latest CentOS version is CentOS 9 Stream, so I guess it would be nice to have it supported by driverkit.

**Feature**

Add support for driverkit on CentOS 9 Stream

**Alternatives**

N/A

**Additional context**

https://github.com/falcosecurity/driverkit/blob/master/pkg/driverbuilder/builder/centos.go

**Comment by dwindsor** [comment]
+1 from me.

Could you please structure your PR in a way similar to #130, with a sample command-line invocation and resultant successful build in the description?
