### ISSUE TITLE
0.9.0 release fails to build AmazonLinux2 drivers

### ISSUE THREAD

**Issue by EXONER4TED** [falcosecurity/driverkit#158]
**Description of Bug**

We tested out 0.9.0 today and noticed a new issue with AmazonLinux2 kernel drivers (specifically for libs version `3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4`). Here's some output from our automation that utilizes driverkit:
```
[ 2022-06-15 16:31:55,897 ] INFO - driverkit.py:137 - Does not exist in bucket! Building: [ scwx_amzn_5.4.68-34.125.amzn2.x86_64_1.ko ]
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
```

It seems the x86_64 binary is built with `CGO_ENABLED=0`.

**Steps to Reproduce**

Can be reproduced with the following using the `amd64` release from the releases page:

1. Download 0.9.0 release from release page: https://github.com/falcosecurity/driverkit/releases/download/v0.9.0/driverkit_0.9.0_linux_amd64.tar.gz
2. Un-tar to `$(pwd)`
3. Spin up linux container (if not on linux):
```
docker run -it -v $(pwd):/test ubuntu:latest
```
4. Run a build for Amazon Linux 2 (with libs version `3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4`):
```
root@ab26a4643071:/test# ./driverkit docker --output-module ./test-amazonlinux2.ko --timeout 520 --target amazonlinux2 --kernelrelease 5.4.186-102.354.amzn2.x86_64 --driverversion=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4 --kernelversion 1
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
```

**Additional Context**
Looking at previous MRs... It seems there was a recent change to set `CGO_ENABLED` to 0: https://github.com/falcosecurity/driverkit/pull/157/files

~~I wonder if setting `CGO_ENABLED=0` only for arm builds would solve the issue? Maybe make the Makefile detect if arm, then `CGO_ENABLED=0`?~~
I tried adding some logic to the Makefile to detect arm vs. x86, and it *does* get x86 building again... But the `mattn/go-sqlite3` lib requires `CGO_ENABLED=1` to run.

**Comment by leodido** [comment]
Thank you, I come late to the party but I confirm that Amazon stores info in an SQLite DB that the AL2 builder needs to download and query...

Therefore PR #157 breaks AL2 builders.
