### ISSUE TITLE
falcosecurity/driverkit-builder-base docker image not available

### ISSUE THREAD

**Issue by vicenteherrera** [falcosecurity/driverkit#19]
**Describe the bug**

When using driverkit against docker daemon, it tries to pull an image that is not publicly available:
`falcosecurity/driverkit-builder-base:1395e08740dcc9b30f9bcb1cc517d14ce340ea9e`

**How to reproduce it**
Execute:
`driverkit docker --output-module falco.ko --kernelversion=81 --kernelrelease=4.15.0-72-generic --driverversion=dev --target=ubuntu-generic`

Output will be:
```
INFO[0000] driver building, it will take a few seconds to complete  processor=docker
FATA[0000] exiting                                       error="Error response from daemon: No such image: falcosecurity/driverkit-builder-base:1395e08740dcc9b30f9bcb1cc517d14ce340ea9e"
```

Execute either:
```
docker pull falcosecurity/driverkit-builder-base
docker pull falcosecurity/driverkit-builder-base:1395e08740dcc9b30f9bcb1cc517d14ce340ea9e
```

Output will be:
`Error response from daemon: pull access denied for falcosecurity/driverkit-builder-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Expected behaviour**

The same command works with a Kubernetes processor:
```
driverkit kubernetes --output-module falco.ko --kernelversion=81 --kernelrelease=4.15.0-72-generic --driverversion=dev --target=ubuntu-generic
INFO[0000] driver building, it will take a few seconds to complete  processor=kubernetes
```

**Screenshots**

Non-applicable

**Environment**

- Falco version: Non-applicable
- System info:
- Cloud provider or hardware configuration:
- OS: MacOs Catalina 10.15.3
- Kernel:
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
- Installation method:
Built driverkit locally on MacOs with `make`

**Additional context**

**Comment by leodido** [comment]
We have to push the docker image, yes 🙂

**Comment by dsever** [comment]
Same here:

```
driverkit-5dccf37f-ee42-4a67-a954-811ac946ad23   0/1     ImagePullBackOff   0          8m29s
```
for 

```
kernelrelease: 4.15.0-23-generic
kernelversion: 25
target: ubuntu-generic
output:
  module: /tmp/falco-ubuntu-generic.ko
  probe: /tmp/falco-ubuntu-generic.o
driverversion: dev
```

Tnx

**Comment by leodido** [comment]
At the moment, as a workaround, you can build it running `make image/buil` from the root of this repo.

**Comment by dsever** [comment]
It works as you proposed.
