### ISSUE TITLE
Multiple builder images

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/driverkit#194]
**Motivation**

As most issues report, like #145  and #126, we are not able to build most recent kernels because our builder image ships with gcc8 as most recent gcc version.

**Feature**

We should be able to properly support multiple builder images, and have an automatic logic to choose the correct one.
The logic should be as simple as possible, matching:
* the requested GCC version (just like we currently have like: `UbuntuGCCVersionFromKernelRelease`
* the requested Clang version (again, we currently have something similar)
* if none of the above is specified, a simple logic based on the requested kernelrelease

While not perfect, this solution is simple, involves little code, and should be quite effective.

**Alternatives**

Another idea could be to host builder images in a different repository, pushed to dockerhub, and avoid having any "automatic" builder image; instead, always relying on the user to provide a config with the correct builder image.
In this sense, it would be a `kernel-crawler` duty to provide in its output json, the correct builder image for each config.
Basically, kernel-crawler should iterate a call to driverkit using each supported builder image, until it successfully builds the kernel, for each crawled kernel.

While tedious, this has the enormous advantage that the "builder image discovery" is made only once, at the kernel-crawler level.
And driverkit will always expect the user to provide a builderimage, making the param mandatory.

This solution is more complex, but has the benefit of (in theory) being able to always discover the right builder image and to generate driverkit configs with already the builder image set.
The downside is:
* much more complex
* involves code somewhere else (not a real downside imo)
* greatly increase kernel-crawler job duration -> i'd expect around some days of work, because we basically run N builds in the worst case (where N is number of builder images) for each crawled kernel...

/cc @dwindsor @LucaGuerra @EXONER4TED @leodido

**Comment by dwindsor** [comment]
> While tedious, this has the enormous advantage that the "builder image discovery" is made only once, at the kernel-crawler level.
And driverkit will always expect the user to provide a builderimage, making the param mandatory.

While I like this idea, this is going to be disruptive to existing users. However, if we're moving towards deprecating crawling from driverkit (in favor of forcing users to always kernel-crawler and provide `--kernelurls` when calling driverkit), we could also do similarly here as well?

I'd be interested to hear from @leodido on this.
