### ISSUE TITLE
Driverkit Features Requests: Enhanced auto-discovery, support concurrent builds for multiple headers and compiler versions 

### ISSUE THREAD

**Issue by incertum** [falcosecurity/driverkit#196]
**Motivation**
---

- Augment functionality for primary use case (compile one driver for one kernel build using recommended compiler version).
- Add functionality to cover more use cases, for instance https://github.com/falcosecurity/libs/pull/524 or https://github.com/falcosecurity/libs/issues/531.

**Feature**
---

### Primary Use Cases

`[001]` Builder Containers

- Big +1 https://github.com/falcosecurity/driverkit/issues/194, need multiple builder images. How about covering clang-5.0 to latest and gcc-5 to latest. Could be 2-4 containers toggled within driverkit based on a knowledge base, see also https://github.com/falcosecurity/kernel-crawler/issues/36 responding to https://github.com/falcosecurity/driverkit/issues/194.

`[002]` Args

- arg `kernelurls` can be misleading, how about introducing `kernelheadersurls` or `headersurls` instead?
- new arg, option to automatically name driver artifact like `kernelrelease` `$(uname -r).<extension>`.
- arg `driverversion`, more options
  - pass local dir
  - pass local file `.tar.gz` (extracts top level libs)
  - pass url `.tar.gz` (extracts top level libs)

---

### Extended Use Cases

Extensions that deviate from the primary use case can be useful for `dev`, `test`, `debug` and `research` or CI integration of driver sanity tests.

`[003]` Concurrency support

- Concurrently download and extract header packages for re-use when re-building many driver artifacts -> output is a directory with subdirectories like:

```bash
❯ tree -L 5 /tmp/headers
/tmp/headers
├── 5.15.59-051559-generic
│   ├── control.tar.zst
│   ├── data.tar.zst
│   ├── debian-binary
│   └── usr
...
│       └── src
│           └── linux-headers-5.15.59-051559
...
└── kernel-ml-devel-5.19.0-1.el7.elrepo.x86_64
    └── usr
        └── src
            └── kernels
                └── 5.19.0-1.el7.elrepo.x86_64

```

- Concurrently compile driver for each kernel header passed (multiple `kernelheadersurls`, auto-select correct container)
- Concurrently compile driver for each kernel header passed for each compiler version passed (multiple `kernelheadersurls`, multiple `compilerversions` - overwrites auto-selection , multiple `drivertypes` even)

```bash

├── clang-10
│   └── 5.19.0-1.el7.elrepo.x86_64.o
├── clang-14
│   ├── 5.15.59-051559-generic.o
│   └── 5.19.0-1.el7.elrepo.x86_64.o
├── clang-5.0
│   └── 5.19.0-1.el7.elrepo.x86_64.o
├── gcc-10
│   └── 5.19.0-1.el7.elrepo.x86_64.ko
└── gcc-5
    └── 5.19.0-1.el7.elrepo.x86_64.ko
...
```

Possible new args supporting various scenarios:

- new arg `kernelheadersdirs` - local dir for one extracted kernel header
- new arg `kernelheaderssubdirs` - local dir with subdirs - each subdir is one extracted kernel header
- new arg `kernelheadersfile` as extension to `kernelheadersurls`, 
  - file that contains one url per line (ubuntu really complicates things given 2 headers packages per kernel ... )
- ... 

Can see that a balance between avoiding confusion and more functionality needs to be found.

**Comment by incertum** [comment]
> > arg kernelurls can be misleading, how about introducing kernelheadersurls or headersurls instead?
> 
> How about just `headers`, so we have convergence between this and kernel-crawler? The new proposed in kernel-crawler refers to kernel headers packages as just `headers`:


Yes just `headers` would be amazing! Re all other fields and naming, probably worth another round of discussion once everything gets refactored.

Additional note: Some end users may be less familiar with kernel development. Perhaps a small paragraph explaining essentials even in greater detail could help? 
- Be very clear to explain that end user should go to kernel crawler file and pass the packages from `headers` and @dwindsor good call which the renaming you suggested it will be an easy 1:1 mapping.
- In addition something like ... to build the driver all you need is those headers packages ... `bpf` uses clang/llvm as compiler while `kmod` uses gcc ... if you wish to test this in a VM, kernel crawler now also exposes `kernels` which are the actual kernel package you install to then re-boot into the desired kernel. @dwindsor @FedeDP?

**Comment by FedeDP** [comment]
Hi @incertum !
Thanks for this feature request :) 

> Big +1 https://github.com/falcosecurity/driverkit/issues/194, need multiple builder images. How about covering clang-5.0 to latest and gcc-5 to latest. Could be 2-4 containers toggled within driverkit based on a knowledge base

I am not sure i understood everything well; btw IMO i think that we only need to cover GCC matrix; possibly we only need just one more builder image for newest kernels (with like gcc 10+); as far as i know, we are pretty stable building kernels <5.10. Here @EXONER4TED did some great tests for  #161, perhaps he has some inputs!

Instead, Clang has no such issues; we can build everything with current clang 12 and we should be fine!

> arg kernelurls can be misleading, how about introducing kernelheadersurls or headersurls instead?

Mmh i am not sure i get it either :laughing: i mean, we only need kernel headers, therefore i chose the `kernelurls` naming. Do we need any other urls?

> new arg, option to automatically name driver artifact like kernelrelease $(uname -r).<extension>.

I am not sure if this is really needed, i mean, what's its use case?

> arg driverversion, more options

This is a little-effort feature that IMO can be easily implemented! Are you willing to work on this? :)

> Concurrency support

Ugh i fear this! Driverkit was conceived as a simple project with a "single run -> single driver" logic.
I am not sure such a feature would help us, really. I only see the complexity it would bring on the table :/

**Comment by dwindsor** [comment]
> Augment functionality for primary use case (compile one driver for one kernel build using recommended compiler version).

Driverkit [0.10.1](https://github.com/falcosecurity/driverkit/releases/tag/v0.10.1) was just released and has the "multiple builders" feature which should address some points of your use case.
