### ISSUE TITLE
Multiple ubuntu kernel headers cannot be found

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/driverkit#200]
**Describe the bug**

As title says; some examples:
```
{
      "kernelversion": "2",
      "kernelrelease": "5.18.0-1002-oracle",
      "target": "ubuntu"
}
{
      "kernelversion": "1",
      "kernelrelease": "5.19.0-1001-lowlatency",
      "target": "ubuntu"
}
{
      "kernelversion": "24~20.04.3",
      "kernelrelease": "5.15.0-24-lowlatency-hwe-5.15",
      "target": "ubuntu"
}
```
These all lead to 
```
FATA exiting                                       error="kernel headers not found"
```
I think there is some sort of issue with current `fetchUbuntuKernelURL` (possibly some patterns are missing).

@EXONER4TED @dwindsor

**Comment by EXONER4TED** [comment]
I promise I will get to looking at this 😅 I've been on family leave, and now am moving houses, but that wraps up this week. I should actually be back in some capacity here in the next couple weeks 😄

**Comment by FedeDP** [comment]
No problem sir :house: :rocket:

**Comment by EXONER4TED** [comment]
I'm looking into this now. For the first example, it looks like `mirrors.edge.kernels.org` doesn't have oracle-5.18 :/

From their site:

[linux-oracle/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle/)                                      21-Mar-2023 17:01       -
[linux-oracle-5.0/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.0/)                                  18-Mar-2020 11:13       -
[linux-oracle-5.11/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.11/)                                 08-Feb-2022 12:07       -
[linux-oracle-5.13/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.13/)                                 15-Jun-2022 11:43       -
[linux-oracle-5.15/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.15/)                                 15-Mar-2023 23:44       -
[linux-oracle-5.3/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.3/)                                  27-Jul-2020 18:23       -
[linux-oracle-5.4/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.4/)                                  18-Feb-2023 23:34       -
[linux-oracle-5.8/](https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.8/)                                  06-Aug-2021 18:15       -

... and `linux-oracle` doesn't have any 5.18

Will keep looking into the others.

**Comment by EXONER4TED** [comment]
Yea... `kernel-crawler` is unable to crawl for these either. My gut says pulled kernels...

```
╰─❯ cat ubuntu.json | grep 5.18.0-1002-oracle

╰─❯ cat ubuntu.json | grep 5.19.0-1001-lowlatency

╰─❯ cat ubuntu.json | grep 5.15.0-24-lowlatency-hwe-5.15

```

**Comment by EXONER4TED** [comment]
I can confirm this is not missing headers patterns though. Taking the `ubuntu-oracle` example above, here are all of the URL subpaths it attempts to crawl:
```
[https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64_all.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux/linux-oracle-headers-5.18.0-1002_5.18.0-1002.2_all.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64_all.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle/linux-oracle-headers-5.18.0-1002_5.18.0-1002.2_all.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.18/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64_all.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.18/linux-headers-5.18.0-1002-oracle_5.18.0-1002.2_amd64.deb https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-oracle-5.18/linux-oracle-headers-5.18.0-1002_5.18.0-1002.2_all.deb]
```
The URL subpaths look like:
```
main/l/linux/
main/l/linux-oracle/
main/l/linux-oracle-5.18
```
Which are the correct paths to go down, but the hosting site just literally doesn't have `linux-oracle-5.18` and doesn't have that specific kernel under `linux-oracle`... So the headers patterns are correct, but the kernel just doesn't exist anymore.

**Comment by FedeDP** [comment]
So, it seems like i was actually testing against pulled kernels? 
Fact is, today crawler is unable to crawl for them, but the test was made ~20th August :laughing: who knows!

I think we can close this one and reopen it eventually if anyone comes up with issues!
Thank you for your investigation @EXONER4TED !
/close
