### ISSUE TITLE
Flatcar support

### ISSUE THREAD

**Issue by mazzy89** [falcosecurity/driverkit#21]
**Motivation**

Support CoreOS/Flatcar 

 
**Feature**

As discussed in here https://github.com/falcosecurity/falco/issues/1075 Flatcar requires some modification to the OS to let Falco install the kernel module 

**Alternatives**

**Additional context**

Discussed this with @leogr that soon driverkit becomes the way to install correct driver. I would like to contribute in this regard for the OS Flatcar. CoreOS is In EOL.

I'm going to partecipate to the community meeting today.

**Comment by leogr** [comment]
IIRC, as discussed during the community call the best approach should be to add a new target `flatcar` [here](https://github.com/falcosecurity/driverkit/tree/master/pkg/driverbuilder/builder).

**Comment by mazzy89** [comment]
I will work on this in the upcoming days. Sorry it is taking a bit longer.
