### ISSUE TITLE
Support linuxkit

### ISSUE THREAD

**Issue by leodido** [falcosecurity/driverkit#22]
**Motivation**

It would be useful to support linuxkit which is used by some popular tools (eg., kind).

**Feature**

Verify whether the `vanilla` target works for linuxkit or not, and in such case document it.

Or, create a explicit target for linuxkit.

**Comment by leodido** [comment]
So, `vanilla` target works fine in building the kernel module for kernel 4.19.x with the correct `kernelconfigdata` (see [here]()).

But, since the linuxkit kernel has `CONFIG_GCC_PLUGIN_RANDSTRUCT` set to y ([ref](https://github.com/linuxkit/linuxkit/blob/badd7910723330b2be03e650a0f50de0b527de7b/kernel/config-4.19.x-x86_64#L773)), the module can't be inserted.

**Comment by leodido** [comment]
At this point the solution COULD be creating a new target for linuxkit only that grabs the kernel source used by linuxkit from here: https://github.com/linuxkit/linuxkit/blob/badd7910723330b2be03e650a0f50de0b527de7b/kernel/Dockerfile#L207

And, then, use this rather that downloading headers from kernel.org

**Comment by leodido** [comment]
An update on this topic.

I've been able to compile the falco kernel module for linuxkit from driverkit but the RANDSTRUCT is different.

```
[117609.155366] falco: version magic '4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_ca499a489906997cbc0f103b5b7d8719e63a8fd486f81bab45f73c9034b593a9' should be '4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_b46c484ab1aef9320d79d3c33cc40c4a3a27d813cd83b5552fa8c0cfa8d16c9f'
```

**Comment by leodido** [comment]
Hmmm

```
bash-5.0# cat include/generated/randomize_layout_hash.h 
#define RANDSTRUCT_HASHED_SEED "ca499a489906997cbc0f103b5b7d8719e63a8fd486f81bab45f73c9034b593a9"
bash-5.0# cat scripts/gcc-plugins/randomize_layout_seed.h 
const char *randstruct_seed = "00d5bafce2af4e27a2cec39d54cab12e36782cda4b7fd4e098073a657c0076e4";
```

**Comment by leodido** [comment]
Ok, I built linuxkit/kernel:4.19.76 from source and this is what I have in it.

```
bash-4.4# cat include/generated/randomize_layout_hash.h #define RANDSTRUCT_HASHED_SEED "0f3718d0c183f9f9156c8e429f543cbf8069b77142d925c4b0e2beefa689bdaa"
bash-4.4# cat scripts/gcc-plugins/randomize_layout_seed.h 
const char *randstruct_seed = "0ec28fff46f76e4fec355a1ef802da6812c400403d2ef96a3f8eeadf39d0a810";
```

Next step: try to use them to compile the Falco kernel module with the correct `RANDSTRUCT_PLUGIN_<hash>`

**Comment by yashbhutwala** [comment]
@leodido the image [here](https://hub.docker.com/layers/docker/for-desktop-kernel/4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64/images/sha256-c42bff3d5f285dcb1dde0937a8b99e2f51f1f764bd9b847c5d188fd02bb74136?context=explore) as described in [this comment](https://github.com/docker/for-win/issues/6099#issuecomment-602665387) should unblock you 😄

**Comment by leodido** [comment]
Will give it a shot soon! 

Thanks Yash! 🤗

**Comment by leodido** [comment]
Okay, that image should fix the issue caused by a different `RANDSTRUCT_HASHED_SEED`.

I did a quick try:

```bash
docker create --name linux docker/for-desktop-kernel:4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64 /bin/sh
mkdir -p /tmp/kernel-docker4desktop
docker cp linux:/kernel-dev.tar /tmp/kernel-docker4desktop/kernel-dev.tar       
tar xvf kernel-dev.tar 
cd usr/src/linux-headers-4.19.76-linuxkit
cat include/generated/randomize_layout_hash.h
$ #define RANDSTRUCT_HASHED_SEED "b46c484ab1aef9320d79d3c33cc40c4a3a27d813cd83b5552fa8c0cfa8d16c9f"
```

As you can see, the seed now matches!  🎉 

This should allow our kernel module to be inserted without any trouble.

At this point we have some possible paths:

1. wait they fix the seed in their docker image (to be the same that `linuxkit/kernel:4.19.76` ships)
     1. at that point the code on `feat/linuxkit` branch should automatically work and ready to be merged in (aside from some refinements to the code style etc.)
2. create, with the same mechanism, in `feat/linuxkit` branch a (temporary?) target for `docker-for-desktop` which uses the exact same mechanism for plain linuxkit but fetches the `kernel-dev.tar` from other docker images
    1. in this case we need a way to make kernel releases to docker images to use (e.g, docker/for-desktop-kernel:4.19.76-d665d2cbc4fe70f8ab08ba2cd82d052e41d2a704-amd64)

Personally, I'd prefer plan 2.

Then, in the future, in case there will be no more need to distinguish we can remove the distinct target, or just update the map kernels <-> docker images shipping correct seed, or both things (in case the seeds get fixed into the images) :)

What do y'all think?

**Comment by yashbhutwala** [comment]
2. sounds good to me!  😄
