### ISSUE TITLE
Cannot build 6.X drivers

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/driverkit#242]
**Describe the bug**

The build fails with `DEBU (Failed to parse base BTF 'vmlinux': -22`.
It seems around 6.X multiple distros added support for generating BTF when building kmod too; this is breaking the build through the builder images.
There is no way to disable this behavior; the issue has been seen on Fedora and Arch.

See: https://github.com/falcosecurity/driverkit/pull/233#issuecomment-1299995485

**Comment by FedeDP** [comment]
Ok this is funny; i can trigger the issue only when passing `--builderimage auto:master` option; if i instead rely on the default builderimage, that, when compiling from master should be exactly the same, it works fine.
See:
```
./_output/bin/driverkit docker --kernelrelease 6.0.1.arch1-1 --target arch --output-module /tmp/arch.ko  --output-probe /tmp/arch.o
INFO driver building, it will take a few seconds   processor=docker
INFO kernel module available                       path=/tmp/arch.ko
INFO eBPF probe available                          path=/tmp/arch.o
```
In debug mode i can see that it is using `image="docker.io/falcosecurity/driverkit-builder_bookworm:adddc98".

But:
```
./_output/bin/driverkit docker --kernelrelease 6.0.1.arch1-1 --target arch --output-module /tmp/arch.ko  --output-probe /tmp/arch.o --builderimage auto:master
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="Error: No such container:path: b68d9af17bf958291b4e84f48ffa0149903b8bc595b1b7bc66f6276750f1195c:/tmp/driver/module.ko"
```
and in debug mode i see `image="docker.io/falcosecurity/driverkit-builder_bookworm:master"` and the aforementioned failure: `DEBU (Failed to parse base BTF 'vmlinux': -22`.

Indeed the 2 images are different (have different shasum O.O)!!

**Comment by FedeDP** [comment]
So, it turns out i was using an out of date master builder image:
`"Created": "2022-09-16T13:27:44.824596284Z",`
I pulled to latest and it now works.

@dwindsor perhaps this is the same issue that was hitting you?

**Comment by dwindsor** [comment]
Ahh interesting! I will try this when I get back. Off the top of my head, I think the issue we were seeing was a missing symbol, but am not immediately sure.. =)

**Comment by FedeDP** [comment]
I think we can close this one; there is no issue related to the BTF and 6.x drivers.
/close
