### ISSUE TITLE
Error building Rocky Linux with kernel 4.18.0-372.26.1.el8_6.x86_64

### ISSUE THREAD

**Issue by jgornowich** [falcosecurity/driverkit#245]
**Describe the bug**

I am trying to use the driverkit to build the falco kernel module against Rocky 8.6 with a kernel version of 4.18.0-372.26.1.el8_6.x86_64.  In attempting to do so I get the error message: 

`error="kernel headers not found" `

Looking at the driverbuilder for rocky linux: https://github.com/falcosecurity/driverkit/blob/4e741b78b6b093746ed84ffbe607c3b7220da1a4/pkg/driverbuilder/builder/rocky.go

It looks like the base url search path is: 
http://download.rockylinux.org/pub/rocky/

But according to the details at: 
http://download.rockylinux.org/pub/rocky/8.6/

We can see a README.txt that specifies that older rocky release's get moved to their vault.  

```bash
This content has been moved to the Rocky Linux Vault

https://dl.rockylinux.org/vault/rocky/8.6/
```
So I guess what that means is somehow there will have to be support to search the vault and the regular public download path. I am not sure if this needs to be conditional or can just search them both in all cases.  

I also noticed in this driverbuilder for Rocky that the most recent 8.7 release version was missing from the `rockyReleases` list. 

**How to reproduce it**

I am using the following build configuration file contents: 

```bash
kernelrelease: 4.18.0-372.26.1.el8_6.x86_64
kernelversion: 1
target: rocky
output:
  module: /tmp/falco-rocky-4.18.0-372.26.1.el8_6.ko
  probe: /tmp/falco-rocky-4.18.0-372.26.1.el8_6.o
driverversion: master
```
And running the following command: 

`/driverkit/_output/bin/driverkit docker -c rocky-4.18.0-372.26.1.el8_6.yaml -l debug`

**Expected behavior**

It should build correctly like the current version of Rocky 8.7 does with kernel 4.18.0-425.3.1.el8 does. 

**Additional context**

Also, I went in and made the modification to the `rocky.go` file to just use the vault url to test it out, rebuilt the driverkit package, and got the following output and error:  

```bash
INFO using config file                             file=rocky-4.18.0-372.26.1.el8_6.yaml
DEBU running with options                          arch=amd64 driverversion=master kernelrelease=4.18.0-372.26.1.el8_6.x86_64 kernelversion=1 output-module=/tmp/falco-rocky-4.18.0-372.26.1.el8_6.ko output-probe=/tmp/falco-rocky-4.18.0-372.26.1.el8_6.o repo-name=libs repo-org=falcosecurity target=rocky
INFO driver building, it will take a few seconds   processor=docker
DEBU doing a new docker build                     
DEBU kernel header url found                       url="https://dl.rockylinux.org/vault/rocky/8.6/BaseOS/x86_64/os/Packages/k/kernel-devel-4.18.0-372.26.1.el8_6.x86_64.rpm"
DEBU proposedGCC=8.0.0                             image=buster targetGCC=8.0.0
DEBU proposedGCC=9.0.0                             image=bullseye targetGCC=8.0.0
DEBU proposedGCC=11.0.0                            image=bookworm targetGCC=8.0.0
DEBU foundGCC=8                                    targetGCC=8.0.0
DEBU pulling builder image                         arch=amd64 image="docker.io/falcosecurity/driverkit-builder_buster:4e741b7.dirty"
FATA exiting                                       error="Error response from daemon: manifest for falcosecurity/driverkit-builder_buster:4e741b7.dirty not found: manifest unknown: manifest unknown"    
```
I am not exactly sure what this error message is telling me or where to start looking to see what went wrong.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
>  I am not sure if this needs to be conditional or can just search them both in all cases.

Yep, you can just search them both, basically appending it after the for cycle, [here](https://github.com/falcosecurity/driverkit/blob/master/pkg/driverbuilder/builder/rocky.go#L75).

> Also, I went in and made the modification to the rocky.go file to just use the vault url to test it out, rebuilt the driverkit package, and got the following output and error:

Yep, you should enforce the usage of the master tag for builder images, by passing additional `--builderimage auto:master`

**Comment by jgornowich** [comment]
Thank you.  Adding the `--builderimage auto:master` argument to the driverkit command worked for what I was doing.  Can you provide me with a brief explanation of what that flag does, and if its required to use that every time I am running with a locally modified driverkit application?

For the others, adding the extra url and extra rocky version, should I just create a PR for those?

**Comment by FedeDP** [comment]
> For the others, adding the extra url and extra rocky version, should I just create a PR for those?

Yay, thank you very much for the fix!

> Can you provide me with a brief explanation of what that flag does, and if its required to use that every time I am running with a locally modified driverkit application?

Of course; since some months, driverkit supports multiple builder images that are runtime chosen based on the kernel major version that you are trying to build.
The default value for the builder image is to use the automatic algorithm, enforcing as image tag the commit hash.
Since you had local changes, the commit hash was:
> DEBU pulling builder image                         arch=amd64 image="docker.io/falcosecurity/driverkit-builder_buster:4e741b7.dirty"

(note the `.dirty`), and it was of course not available.
By enforcing the usage of `auto:master` builder image, you are telling driverkit to use the automatic algorithm enforcing the `master` image tag (that is automatically pushed for the supported builder images as soon as a PR is merged into master).

Note that you can also directly use a fixed image, like, in your case, `--builderimage docker.io/falcosecurity/driverkit-builder_buster:master` would have worked too!
Here is a small doc file (but is mostly technical): https://github.com/falcosecurity/driverkit/blob/master/docs/builder_images.md
Since it is quite a new feature, we need to improve the doc :/ Sorry!

**Comment by jgornowich** [comment]
Thank you very much for the explanation, I think I understand from a high level now why this is required and what is pertains too.  I will take a look at the doc that you linked as well.  

PR has been generated.  Hopefully this is in a acceptable format for approval, this was my first contribution here, so let me know if there is anything I need to update or fix.

**Comment by FedeDP** [comment]
The PR is fine! Thank you very much :) 
You just need to add the DCO to the commit and we are fine!

**Comment by jgornowich** [comment]
Done!
