### ISSUE TITLE
Driver loading problem

### ISSUE THREAD

**Issue by Shifna12Zarnaz** [falcosecurity/driverkit#269]
For building the driver,followed the steps in this documentation
https://falco.org/blog/falco-driverkit-debian-docker/#launching-falco-with-the-new-driver

I am facing an issue while executing this step
./driverkit/driverkit docker -c debian.yaml

while executing this command,getting output as
INFO using config file                             file=debian.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting       error=kernel headers not found

kindly help me in solving this issue

**Comment by Shifna12Zarnaz** [comment]
And also while using minikube cluster and
while installing falco through helm when giving this command
helm install falco falcosecurity/falco --set driver.kind=ebpf --namespace falco --create-namespace
my pod is in running state....But in devcluster or anyother cluster,when trying to install falco with this command getting crash loopbackoff state

This is the debian.yaml file
target: debian
driverversion: 2.0.0+driver
kernelrelease: 5.19.0-40-generic
kernelversion: 4122.04.1-Ubuntu
output:
module: ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_4122.04.1-Ubuntu.ko
probe: ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41~22.04.1-Ubuntu.o

**Comment by Shifna12Zarnaz** [comment]
Hi...after executing uname --all,got the below output
Linux hp-HP-250-G8-Notebook-PC 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Now after changing values in debian.yaml,the debian.yaml looks like
target: debian
driverversion: 2.0.0+driver
kernelrelease: 5.19.0-41-generic
kernelversion: 42~22.04.1-Ubuntu
output:
  module: ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41~22.04.1-Ubuntu.ko
  probe:  ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41~22.04.1-Ubuntu.o

**Comment by FedeDP** [comment]
Yep `42` is the right versioning.
Is it working now?

**Comment by Shifna12Zarnaz** [comment]
No,it is not working..still facing the same issue.

**Comment by Shifna12Zarnaz** [comment]
Now again after executing the  command ./driverkit/driverkit docker -c debian.yaml,I can see the below output,
INFO using config file                             file=debian.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="kernel headers not found"


Can you share the exact command  for -l debug? Because am getting -l command not found

**Comment by FedeDP** [comment]
`./driverkit/driverkit docker -c debian.yaml -l debug`

**Comment by Shifna12Zarnaz** [comment]
![Screenshot from 2023-05-02 16-10-50](https://user-images.githubusercontent.com/113975569/235645316-640160d3-ebd5-4015-bfd9-5061533def52.png)


/driverkit/driverkit docker -c debian.yaml -l debug
INFO using config file                             file=debian.yaml
DEBU running with options                          arch=amd64 driverversion=2.0.0+driver kernelrelease=5.19.0-41-generic kernelversion="42~22.04.1-Ubuntu" output-module="./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41~22.04.1-Ubuntu.ko" output-probe="./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41~22.04.1-Ubuntu.o" repo-name=libs repo-org=falcosecurity target=debian
INFO driver building, it will take a few seconds   processor=docker
DEBU doing a new docker build                     
FATA exiting                                       error="kernel headers not found"

**Comment by FedeDP** [comment]
Did you update your debian.yaml to only use `42` as kernelversion?

**Comment by FedeDP** [comment]
Also please, use code blocks when posting code or shell output; it is much more readable!

**Comment by Shifna12Zarnaz** [comment]
But I guess,you have driver for version 40.But in my case, version is 42.Will it cause any issue?.And also after downloading the driver,how to use it?Will  this driver supports anycluster like devcluster also?

**Comment by FedeDP** [comment]
You are still using 
`kernelversion: 42~22.04.1-Ubuntu`
while you should be using
`kernelversion:42`

```
target: debian
driverversion: 2.0.0+driver
kernelrelease: 5.19.0-41-generic
kernelversion: 42
output:
  module: ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41.ko
  probe: ./drivers/2.0.0+driver/x86_64/falco_debian_5.19.0-40-generic_41.o
```
This should work fine.
Remember also that kernel headers discovery algorithm is best effort, that's why we developed the [kernel-crawler](https://github.com/falcosecurity/kernel-crawler) tool, that actually crawls multiple distros kernels and outputs a driverkit like format list.

Btw latest kernel-crawler run discovered the new kernel: https://falcosecurity.github.io/kernel-crawler/?arch=x86_64&target=Ubuntu&search=5.19.0-41-generic and the CI is building the drivers for it: https://prow.falco.org/view/s3/falco-prow-logs/logs/build-new-drivers-ubuntu-generic-5-postsubmit/1653369276062502912

The new driver should be available in a couple of hours.

> Will it cause any issue?.And also after downloading the driver,how to use it?Will this driver supports anycluster like devcluster also?

Yep, it won't load if the kernelversion is different. But you are soon going to find the new prebuilt drivers for your version tjhat will work :)

**Comment by Shifna12Zarnaz** [comment]
I want to install falco through helm in dev cluster.So after downloading driver,what should I do next?

**Comment by FedeDP** [comment]
You should then follow: https://github.com/falcosecurity/charts/tree/master/falco#adding-falcosecurity-repository

Again, as soon as the driver is available on download.falco.org, everything will go smoothly.

**Comment by FedeDP** [comment]
The driver is now available on download.falco.org: https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=ubuntu-generic&arch=x86_64&kind=kmod&search=falco_ubuntu-generic_5.19.0-42-generic_43.ko

**Comment by Shifna12Zarnaz** [comment]
Hi....Again facing Crash LoopBack off issue.
Below is my values.yaml file
`falco:
  driver:
    name: "https___download.falco.org_driver%2F4.0.0%2Bdriver%2Fx86_64%2Ffalco_ubuntu-generic_5.19.0-42-generic_43.ko"
    source: "file://home/shifnazarnaz/falco-install/https___download.falco.org_driver%2F4.0.0%2Bdriver%2Fx86_64%2Ffalco_ubuntu-generic_5.19.0-42-generic_43.ko"
`
After giving ` helm install falco falcosecurity/falco -f values.yaml -n falco`

My pods are in crashLoop backoff state

**Comment by Shifna12Zarnaz** [comment]
Hi....Again facing Crash LoopBack off issue.
Below is my values.yaml file
```
falco: 
driver: 
name: "https___download.falco.org_driver%2F4.0.0%2Bdriver%2Fx86_64%2Ffalco_ubuntu-generic_5.19.0-42-generic_43.ko" source: "file://home/shifnazarnaz/falco-install/https___download.falco.org_driver%2F4.0.0%2Bdriver%2Fx86_64%2Ffalco_ubuntu-generic_5.19.0-42-generic_43.ko
```" 
After giving  helm install falco falcosecurity/falco -f values.yaml -n falco

My pods are in crashLoop backoff state

**Comment by Shifna12Zarnaz** [comment]
[
![Screenshot from 2023-05-03 12-03-41](https://user-images.githubusercontent.com/113975569/235846364-bec02e4f-3a00-41d4-9305-32669ac997cb.png)
](url)

Here as you can see my problem has not solved,still am facing crashloopback off state,after using the driver for my kernel version.So kindly help me in solving this issue

**Comment by FedeDP** [comment]
Yes but the opening post is talking about:
> For building the driver,followed the steps in this documentation
> https://falco.org/blog/falco-driverkit-debian-docker/#launching-falco-with-the-new-driver
> 
> I am facing an issue while executing this step
> ./driverkit/driverkit docker -c debian.yaml


But ok; if you install Falco through the helm chart there is no need to download any driver locally; your values.yaml is weird looking (name and source for driver?)

Have you tried just following https://github.com/falcosecurity/charts/tree/master/falco#adding-falcosecurity-repository?

Quoting from that page:
> The driver should be installed on the node where Falco is running. The kernel module (default option) and the eBPF probe are installed on the node through an init container (i.e. falco-driver-loader) that tries to build drivers to download a prebuilt driver or build it on-the-fly or as a fallback. The Modern eBPF probe doesn't require an init container because it is shipped directly into the Falco binary. However, the Modern eBPF probe requires a kernel version equal to or greater than 5.8.

**Comment by mrak-** [comment]
after kernel update. I can't build drivers 
my debian.yaml:
target: debian
driverversion: 5.0.1+driver
kernelrelease: 5.18.16-1-amd64
kernelversion: 1
output:
  module: drivers/5.0.1+driver/x86_64/falco_debian_5.18.16-1-amd64_1.ko
  probe:  drivers/5.0.1+driver/x86_64/falco_debian_5.18.16-1-amd64_1.o

<img width="675" alt="Screenshot 2023-06-08 at 13 48 17" src="https://github.com/falcosecurity/driverkit/assets/7160988/9b5f0731-804f-4c29-a740-a36d8afaeb1c">

**Comment by FedeDP** [comment]
Can you share debug log (-l debug at cmdline)?

**Comment by FedeDP** [comment]
Uh i see it is not finding kernelurls. Are you sure that is the correct kernel release?

**Comment by FedeDP** [comment]
Can you share your `uname -a`?

**Comment by mrak-** [comment]
5.18.0-0.deb11.4-amd64

**Comment by mrak-** [comment]
yeah, its uname -r

**Comment by mrak-** [comment]
I was able to download the driver from DRIVER_REPO but Falco is not start 
I have an error:
<img width="1011" alt="image" src="https://github.com/falcosecurity/driverkit/assets/7160988/0ccf2517-6c41-48c6-804e-b5611acfe0c0">

**Comment by FedeDP** [comment]
/close

This has nothing to do with driverkit. Feel free to open an issue on Falco repository.
