### ISSUE TITLE
Unable to install falco in anyother cluster other than minikube cluster

### ISSUE THREAD

**Issue by Shifna12Zarnaz** [falcosecurity/driverkit#270]
Using minikube cluster,when trying to install falco through helm with the below command
helm install falco falcosecurity/falco --set driver.kind=ebpf --namespace falco --create-namespace
my pod is in running state....But in devcluster or anyother cluster,when trying to install falco with this command getting crash loopbackoff state.Pls help me to solve this issue

**Comment by FedeDP** [comment]
Hi!
This does not belong to driverkit repo; it should be opened against Falco repository.

**Comment by alacuku** [comment]
Duplicate of https://github.com/falcosecurity/charts/issues/485

**Comment by FedeDP** [comment]
Closing this one.
/close
