### ISSUE TITLE
Cannot download kernel headers for correct kernel version on Fedora CoreOS

### ISSUE THREAD

**Issue by acidghost** [falcosecurity/driverkit#351]
**Describe the bug**

I've managed to run the Falco agent in a container (Kubernetes) on Fedora CoreOS 40 with `ebfp` driver type, but after an OS upgrade from version `40.20240701.3.0` to `40.20240709.3.1` (which also updated the kernel), I started seeing the following error in the container that's trying to install the driver.

```
* Setting up /usr/src links from host
2024-08-10 08:24:50 INFO  Running falcoctl driver config
                      ├ name: falco
                      ├ version: 7.2.0+driver
                      ├ type: ebpf
                      ├ host-root: /host
                      └ repos: https://download.falco.org/driver
2024-08-10 08:24:50 INFO  Committing driver config to k8s configmap
                      └ namespace: default
2024-08-10 08:24:50 INFO  Storing falcoctl driver config
2024-08-10 08:24:50 INFO  Running falcoctl driver install
                      ├ driver version: 7.2.0+driver
                      ├ driver type: ebpf
                      ├ driver name: falco
                      ├ compile: true
                      ├ download: true
                      ├ target: fedora
                      ├ arch: x86_64
                      ├ kernel release: 6.9.7-200.fc40.x86_64
                      └ kernel version: #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024
2024-08-10 08:24:50 INFO  Removing eBPF probe symlink
                      └ path: /root/.falco/falco-bpf.o
2024-08-10 08:24:50 INFO  Trying to download a driver.
                      └ url: https://download.falco.org/driver/7.2.0%2Bdriver/x86_64/falco_fedora_6.9.7-200.fc40.x86_64_1.o
2024-08-10 08:24:50 WARN  Non-200 response from url. code: 404
2024-08-10 08:24:50 WARN  unable to find a prebuilt driver
2024-08-10 08:24:50 INFO  Trying to compile the requested driver
2024-08-10 08:24:50 INFO  Trying automatic kernel headers download.
2024-08-10 08:24:51 INFO  Trying to build eBPF probe.
+ cd /usr/src/falco-7.2.0+driver
+ echo '* Building eBPF probe'
* Building eBPF probe
+ '[' '!' -d /sys/kernel/debug/tracing ']'
+ echo '* Mounting debugfs'
* Mounting debugfs
+ mount -t debugfs nodev /sys/kernel/debug
+ cd bpf
+ make
make -C /lib/modules/6.9.7-200.fc40.x86_64/build M=$PWD
make[1]: *** /lib/modules/6.9.7-200.fc40.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:23: all] Error 2
2024-08-10 08:24:51 ERROR failed: failed to build all requested drivers
```

After a bit of debugging I found out that while trying to download the kernel headers, it makes a request to
https://mirrors.kernel.org/fedora/updates/40/Everything/x86_64/Packages/k/kernel-devel-6.9.7-200.fc40.x86_64.rpm
which does not exist. I think this is because the mainline Fedora distro (i.e. not CoreOS) has already moved to a newer kernel (6.10.x at the time of writing).

For reference, the URLs are set here https://github.com/falcosecurity/driverkit/blob/9ee5859bb67b56a8b114ce0ac2a0da7cd059ea89/pkg/driverbuilder/builder/fedora.go#L66-L88

If I take a look at the configured package repositories on the CoreOS host I see an interesting one:
```
❯ cat /etc/yum.repos.d/fedora-updates-archive.repo
# This is a repo that contains all the old update packages from the
# Fedora updates yum repository (i.e. the packages that have made it
# to "stable"). This repo is needed for OSTree based systems where users
# may be trying to layer packages on top of a base layer that doesn't
# have the latest stable content. Since base layer content is locked
# the package layering operation will fail unless there are older versions
# of packages available.
#
# This repo is given a high cost in order to prefer the normal Fedora
# yum repositories, which means only packages that can't be found
# elsewhere will be downloaded from here.
[updates-archive]
name=Fedora $releasever - $basearch - Updates Archive
baseurl=https://fedoraproject-updates-archive.fedoraproject.org/fedora/$releasever/$basearch/
enabled=1
metadata_expire=6h
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=True
cost=10000 # default is 1000
```

Trying the `baseurl` https://fedoraproject-updates-archive.fedoraproject.org/fedora/40/x86_64/kernel-devel-6.9.7-200.fc40.x86_64.rpm retrieves the correct headers.

**How to reproduce it**

Run latest stable Fedora CoreOS 40 (see bug description for precise version).

Start container:
`sudo podman run --rm -it --entrypoint bash --privileged --security-opt label=disable --mount type=bind,source=/proc,target=/host/proc,readonly --mount type=bind,source=/boot,target=/host/boot,readonly --mount type=bind,source=/lib/modules,target=/host/lib/modules --mount type=bind,source=/usr,target=/host/usr,readonly --mount type=bind,source=/etc,target=/host/etc,readonly docker.io/falcosecurity/falco-driver-loader:latest@sha256:5d42f7abee1d1bcf82f0cfb322cafeda7ae083b5fbe6cf69cfbabca76e5fc874`

Once in container:
```
falcoctl driver config --type ebpf
falcoctl driver install --compile=true --http-insecure=false --log-level=trace
```

**Expected behaviour**

Correct kernel headers are downloaded and driver is installed.

If kernel headers could not be found in any way, maybe show a clearer description of the error or a warning about not being able to download the headers.

**Screenshots**

N/A

**Environment**

- Falco version:

```2024-08-10T08:48:58+0000: Falco version: 0.38.1 (x86_64)
2024-08-10T08:48:58+0000: Falco initialized with configuration files:
2024-08-10T08:48:58+0000:    /etc/falco/falco.yaml
2024-08-10T08:48:58+0000: System info: Linux version 6.9.7-200.fc40.x86_64 (mockbuild@8d858239ee7c403c892e8a84096b3ce3) (gcc (GCC) 14.1.1 20240620 (Red Hat 14.1.1-6), GNU ld version 2.41-37.fc40) #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024
Falco version: 0.38.1
Libs version:  0.17.2
Plugin API:    3.6.0
Engine:        0.40.0
Driver:
  API version:    8.0.0
  Schema version: 2.0.0
  Default driver: 7.2.0+driver
```
- System info:

```json
{
  "machine": "x86_64",
  "nodename": "254ea178fc6a",
  "release": "6.9.7-200.fc40.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024"
}
```
- Cloud provider or hardware configuration:
- OS:

```
NAME="Fedora Linux"
VERSION="40.20240709.3.1 (CoreOS)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora CoreOS 40.20240709.3.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='40.20240709.3.1'
```
- Kernel: `Linux REDACTED 6.9.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024 x86_64 GNU/Linux`
- Installation method: Kubernetes manifest

**Additional context**

**Comment by FedeDP** [comment]
Hi! Thanks for opening this super detailed issue!
Yes we might just need to add and manage the updates-archive repository, are you willing to open a PR to add it since you already digged into the right code section?
Also, I think we will need to add the repo to falcosecurity/kernel-crawler project so that we discover these kernels and build prebuilt drivers for it!

Last but not least, is there any reason why you are sticking to the old ebpf probe instead of using the modern_ebpf one that does not need to download/build any artifact since it leverages CO-RE kernel technology?

**Comment by acidghost** [comment]
Sure, I can look into it more and open a PR.

> Last but not least, is there any reason why you are sticking to the old ebpf probe instead of using the modern_ebpf one that does not need to download/build any artifact since it leverages CO-RE kernel technology?

Glad you asked as I planned to open another PR :) I'll try to keep it short here, but it's a bit convoluted.

I was trying to deploy Falco in a 2-node cluster of Fedora CoreOS 40 x86-64 and Raspberry Pi 5B w/ official Debian Bookworm. I noticed a warning in the logs complaining that the agent could not update the `ConfigMap`, which is shared among the deployments (2, one for each node as a `DaemonSet`). This was due do a missing `patch` verb in the role (ref. https://github.com/falcosecurity/deploy-kubernetes/blob/d8965966c44c76e1165e4047831a5cc7caab5fb4/kubernetes/falco/templates/role.yaml#L14-L19). After adding it I then noticed that a sort of race would happen where the two deployments would race to update the (shared) Falco configuration to set the driver type to the one it discovered working / preferred to use. Unfortunately the two nodes don't support the same set of driver types, the intersection of the two is plain `ebpf`.

Note that I followed the official manifests:
- config is manually initialized w/ kind `modern_ebpf`: https://github.com/falcosecurity/deploy-kubernetes/blob/d8965966c44c76e1165e4047831a5cc7caab5fb4/kubernetes/falco/templates/configmap.yaml#L25
- driver loader is invoked w/ `auto`: https://github.com/falcosecurity/deploy-kubernetes/blob/d8965966c44c76e1165e4047831a5cc7caab5fb4/kubernetes/falco/templates/daemonset.yaml#L125

For reference, here's the driver type support table for my two nodes:
- Fedora CoreOS 40 x86-64 supports `ebpf` and `modern_ebpf` (`kmod` fails w/ some permission errors which may be due to my setup, I haven't digged in)
- RPI 5B Bookworm supports `ebpf` and `kmod` (`modern_ebpf` fails w/ `libpman: prog 'BPF_TRACE_RAW_TP' is not supported`, which AFAIK means that BPF Type Format is not compiled in the default kernel)

I'm new to Falco so this may not be an issue with it, I might have messed something in my deployment or setup. Is there some obvious config change that I can make to prevent the race condition on updating the `ConfigMap`?

**Comment by FedeDP** [comment]
Oh thanks for the clarification! Yes that's a known falcoctl driver loader issue. Me and @alacuku are aware of that and will hopefully improve the situation in time for the next Falco release :)

**Comment by acidghost** [comment]
In the meantime, what would be the suggested workaround? I can keep the "fix" of setting `ebpf` to get around the race condition, but what about working around getting the kernel headers?

**Comment by acidghost** [comment]
@FedeDP unfortunately I don't think it's possible to add `https://fedoraproject-updates-archive.fedoraproject.org/fedora/` to kernel-crawler because it does not have a `primary_db` field in https://fedoraproject-updates-archive.fedoraproject.org/fedora/40/x86_64/repodata/repomd.xml (I know almost nothing about RPM internals).

**Comment by FedeDP** [comment]
Hi! I was on PTO sorry :D 
> In the meantime, what would be the suggested workaround?

There is unfortunately no workaround for falcoctl right now, we will work on a fix asap!
>  unfortunately I don't think it's possible to add https://fedoraproject-updates-archive.fedoraproject.org/fedora/ to kernel-crawler because it does not have a primary_db field

No problem, i will work on the kernel-crawler myself! Thanks for the driverkit PR!

**Comment by FedeDP** [comment]
Actually, changes needed on kernel-crawler are a bit big; i am not sure it is worth it considering that modern-ebpf driver works successfully; me and Aldo will work on the falcoctl bug asap!
