### ISSUE TITLE
Built Local Container/Feature

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/driverkit#39]
**Motivation**

**Feature**

Can we please have an easy way to build for the current system such that the user does not need to run the `uname` commands?

If we were to create a `driverkit-local` container we could easily generate the configuration file from the system it's running on, and build both the BPF probe and the kernel module.

Then we could add this container to the helm chart or other installation avenues so that the user no longer has to build the driver(s) for Falco manually. 

**Alternatives**

Now I have to SSH into an aws node and install driverkit to get driverkit to build the driver.

**Additional context**

**Comment by kris-nova** [comment]
If you could just do something like this it would be really cool.

```
docker run falcosecurity/driverkit-local-mod:latest     # <-- Installs the kernel moduel 
docker run falcosecurity/driverkit-local-ebf:latest     # <-- Installs the BPF probe
docker run falcosecurity/driverkit-local                # <-- Installs both
```

**Comment by leogr** [comment]
Hey @kris-nova 
IMHO, `driverkit` should not be responsible for installing things, rather `falcoctl` should do that by using driverkit as a library (see https://github.com/falcosecurity/falcoctl/issues/81 ).
WDYT?
