### ISSUE TITLE
Builder for centos

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/driverkit#5]
**Motivation**

According to the survey that we run, CentOS is one of the systems we should target.

**Feature**

Create a new target - namely `centos` - implementing the scripts we need to build the kernel module on such systems.

**Additional context**

![Screenshot 2020-03-04 at 19 40 02](https://user-images.githubusercontent.com/120051/75911510-f8557980-5e4f-11ea-92a2-1d2772d1b4f5.png)

**Comment by leodido** [comment]
@fntlnz no more endpoints, please :)

Also, I like "builde type" 🇮🇹

**Comment by fntlnz** [comment]
@leodido updated! Thank you
