### ISSUE TITLE
Ubuntu : specific kernel headers not found

### ISSUE THREAD

**Issue by robotica72** [falcosecurity/driverkit#64]
Using the example for Ubuntu-generic works, but I am trying to build for Ubuntu 16.04, kernel 4.4.0-142-generic, kernelversion=169

Executing with these options throws: error="specific kernel headers not found"

To reproduce: 
driverkit docker --output-module /tmp/falco.ko  --kernelrelease=4.4.0-142-generic --driverversion=dev --target=ubuntu-generic

**Expected behaviour**
Successful build using the kernel options

Using latest driverkit

- System info:
- OS: Ubuntu 16.04
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"

- Kernel:
Linux kind 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Any ideas why it doesnt like the kernel options to build?

**Comment by leogr** [comment]
Have you tried 
```
driverkit docker --output-module /tmp/falco.ko --kernelversion=168 --kernelrelease=4.4.0-142-generic  --driverversion=dev --target=ubuntu-generic
```
?

Note that your kernelversion seems to be 168, and not 169.

**Comment by robotica72** [comment]
@leogr - Doh!  I didnt notice that typo, Thanks for catching that - changed to 168 (The correct version as you pointed out), and it completed the build.   Thanks again for catching that.

**Comment by leodido** [comment]
Thanks @leogr for noticing this

And thanks @robotica72 for trying `driverkit` :)

/close
