### ISSUE TITLE
Support newer kernels in the CentOS builder

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/driverkit#78]
**Motivation**

Our[ CentOS builder] (https://github.com/falcosecurity/driverkit/blob/master/pkg/driverbuilder/builder/centos.go) does not seem to support kernels other than 2.6 and 3.10

**Feature**

We need to support the newer kernels.
**Alternatives**

**Additional context**

https://github.com/falcosecurity/falco/issues/1433

**Comment by evalsocket** [comment]
@fntlnz I want to pick this. If it is a good first issue
