### ISSUE TITLE
Unable to find kernel headers for debian_5.8.0-1-cloud-amd64_1

### ISSUE THREAD

**Issue by leodido** [falcosecurity/driverkit#79]
**Describe the bug**

By debugging https://github.com/falcosecurity/evolution/issues/43 (more info [here](https://github.com/falcosecurity/evolution/issues/43#issuecomment-759575551), I found that the `debian` builder is not able to find kernel headers for [these prebuild driver configurations](https://github.com/falcosecurity/test-infra/pull/276) (ie., `debian_5.8.0-1-cloud-amd64_1`).

**How to reproduce it**

Run `driverkit docker -c ...` with one of the YAML files [here](https://github.com/falcosecurity/test-infra/pull/276).

**Expected behavior**

To successfully find the kernel headers for that particular debian.

**Screenshots**

<img width="1255" alt="Screenshot 2021-01-13 at 17 39 19" src="https://user-images.githubusercontent.com/120051/104487804-daa78380-55cd-11eb-9d9a-af06fb6c95ed.png">

**Comment by maxgio92** [comment]
I think that this happens also for other kernel versions, like `5.9.0-1-amd64`, reading the [prow](https://github.com/falcosecurity/test-infra) [periodic job logs](https://prow.falco.org/view/s3/falco-prow-logs/logs/build-drivers-debian-periodic/1349551974969774080).
