### ISSUE TITLE
Version flag not working

### ISSUE THREAD

**Issue by leodido** [falcosecurity/driverkit#85]
**Describe the bug**

The `driverkit -v` doesn't output the driverkit version.

**How to reproduce it**

```console
wget -q https://github.com/falcosecurity/driverkit/releases/download/v0.3.0/driverkit_0.3.0_linux_amd64.tar.gz
tar -xvf driverkit_0.3.0_linux_amd64.tar.gz
driverkit -v
```

**Expected behaviour**

To output:

`v0.3.0`

**Screenshots**

![image](https://user-images.githubusercontent.com/120051/105492133-bf1c3700-5cb7-11eb-9e6f-17605ad2fe05.png)

**Additional context**

The release process has the LDFLAGS as you can see [here](https://app.circleci.com/pipelines/github/falcosecurity/driverkit/121/workflows/ee202fd3-f2eb-4855-99b5-6daa34dced27/jobs/174). So this looks very strange.

**Comment by evalsocket** [comment]
@leodido on my local it is working fine

```bash
evalsocket@evalsocket:driverkit ❯ ./_output/bin/driverkit -v                                                                                                                                       
driverkit version v0.3.0-0+2fba205

driverkit! ❯ docker run -it docker.io/falcosecurity/driverkit:v0.3.0 driverkit -v                                             [
driverkit version v0.3.0-0+2fba205

evalsocket@evalsocket:driverkit! ❯ ./dist/driverkit_linux_amd64/driverkit -v                                                                                                                             
driverkit version v0.3.0-0+2fba205
```
