### ISSUE TITLE
Builder for RHCOS

### ISSUE THREAD

**Issue by leodido** [falcosecurity/driverkit#86]
**Motivation**

This [comment](https://github.com/falcosecurity/falco/issues/1505#issuecomment-763430222) explains well - IMHO - why the community might benefit from having a set of prebuilt Falco drivers for RHCOS.

To have such prebuilt drivers, we need a driverkit builder for RHCOS, first of all.

**Feature**

Create a builder for RHCOS.

**Comment by Tamronimus** [comment]
A builder for RHCOS/RHEL 8 still would be very helpful.

**Comment by FedeDP** [comment]
> A builder for RHCOS/RHEL 8 still would be very helpful.

I think you can use vanilla builder passing to it a kernel config; see for example what we do for bottlerocket with kernel-crawler: https://falcosecurity.github.io/kernel-crawler/?arch=x86_64&target=BottleRocket

**Comment by dwindsor** [comment]
Well, for RHEL 8, you'll need access to a system that is registered to receive RHEL entitlements. I'm not sure how it's actually working now?

**Comment by FedeDP** [comment]
Uh i forgot we had a `redhat` builder now :D it was contributed by @johnbrydon !
Gentle ping :)

**Comment by dwindsor** [comment]
Hahaha =)

IIUC, there's no work to be done. If you look at the [example builders](https://code.8labs.io/endpoint/agent/taegis_linux/-/jobs/27208110/artifacts/browse/taegis_linux-build-package/), there's a sample config for RHEL8 (as well as RHEL9!)

![Screenshot 2023-03-02 at 9 25 31 AM](https://user-images.githubusercontent.com/934449/222455963-ad87454a-8be4-414d-af36-08b04c28ce4d.png)

**Comment by FedeDP** [comment]
Oh i see; i completely forget about this :laughing: 
Then i think we can close this one, right?

**Comment by dwindsor** [comment]
I think so! yes
