### ISSUE TITLE
Amazonlinux2 drivers for kernels in extras repositories

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/driverkit#88]
**Motivation**
Amazonlinux2 has a way to enable extras repositories defined [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#extras-library) .

In that way, an user can get a 5.4.x kernel while normally al2 has a 4.19.x

**Feature**

Build the drivers for the extra repos

**Alternatives**

**Additional context**

**Comment by zuc** [comment]
Fixed by #92.
/close
